### ISSUE TITLE
Only showing question

### ISSUE THREAD

**Issue by raizal** [alfredayibonte/QuestionnaireView#2]
Not showing its checkbox/radiobox answer. If it's in EditText mode, only showing an edittext without its answer.

![screenshot 3](https://cloud.githubusercontent.com/assets/1001563/25878465/08c7ed4c-3555-11e7-88fc-17971c27fa83.jpg)

**Comment by alfredayibonte** [comment]
@raizal, EditText option is for you to provide your own answer so ideally the answers options are not to show.

**Comment by RowlandOti** [comment]
@alfredayibonte  this is an awesome library. I have a suggestion regarding this issue. I think it would make much more sense to have in addition an: 

```java
questionnaireViewEditText.addOnTextChangedListener(new TextWatcher() {

          public void afterTextChanged(Editable s) {

          }

          public void beforeTextChanged(CharSequence s, int start, int count, int after) {}

          public void onTextChanged(CharSequence s, int start, int before, int count) {}
       });)
```

This would expand the use case a little bit more. What do you think?

**Comment by alfredayibonte** [comment]
@RowlandOti that's a great suggestion. I will try and add the TextChangedListener. Thanks

**Comment by alfredayibonte** [comment]
@RowlandOti, I have created a branch to add the TextChangedListener, hopefully if I test and nothing breaks,  I would have it merged in master.

**Comment by RowlandOti** [comment]
Sure, no worries. Can't wait to have that feature and many more. Cheers!
